### ISSUE TITLE
[question] Does this work with meteor 1.4?

### ISSUE THREAD

**Issue by darkyen** [robfallows/tunguska-accounts-imgur#1]

**Comment by robfallows** [comment]
Yes it does :smile:

**Comment by darkyen** [comment]
Thanks for confirming, great article, I ended up making https://github.com/darkyen/meteor-auth0 using this (:

**Comment by robfallows** [comment]
Cool - I was thinking of doing an auth0 handler and now I don't need to! :smile:

**Comment by darkyen** [comment]
@robfallows I am still not very happy with mine though, as you won't be able to use Lock with it. Meteor has its own handler for the lock part of the code. Any suggestions?

I thought of using `response_type=code token` which will respond with implicit flow added a code this code can be then used in the same fashion meteor's credentials are used to actually login. (So the id_token would authenticate and the code will allow the  server to fetch any extra credentials its seeking)

My major concern for not going that way, I don't want to implement an OAuth handler myself, the vulnerability surface area would be too high.
